In [1]:
import pandas as pd
import numpy as np

In [ ]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [ ]:
movies.info()
movies['title'][0]

In [ ]:
credits.info()

In [87]:
movie=movies.merge(credits,on='title')

In [88]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [89]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [90]:
movie=movie[['title','genres','id','keywords','overview','production_companies','vote_average','cast','crew','tagline','vote_count']]
movie.head(1)

,title,genres,id,keywords,overview,production_companies,vote_average,cast,crew,tagline,vote_count
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Enter the World of Pandora.,11800

In [91]:
movie.isnull().sum()

title                     0
genres                    0
id                        0
keywords                  0
overview                  3
production_companies      0
vote_average              0
cast                      0
crew                      0
tagline                 844
vote_count                0
dtype: int64

In [92]:
movie["overview"] = movie["overview"].fillna(movie["title"])
movie["tagline"] = movie["tagline"].fillna(movie["title"])
movie.isnull().sum()

title                   0
genres                  0
id                      0
keywords                0
overview                0
production_companies    0
vote_average            0
cast                    0
crew                    0
tagline                 0
vote_count              0
dtype: int64

In [93]:
import ast
def strolist(item):
    l=[]
    for i in ast.literal_eval(item):
        l.append(i['name'])
    return l

def cast(item):
    l=[]
    cnt=0;
    for i in ast.literal_eval(item):
        l.append(i['name'])
        cnt=cnt+1
        if(cnt>5):
          break;
    return l

def crew(item):
    l = []
    for i in ast.literal_eval(item):
        if (i['job'] == 'Director') or (i['job']=='Writer'):
            l.append(i['name'])
    return l

In [94]:
movie['genres']=movie['genres'].apply(strolist)
movie['keywords']=movie['keywords'].apply(strolist)
movie['production_companies']=movie['production_companies'].apply(strolist)
movie['cast']=movie['cast'].apply(cast)
movie['crew']=movie['crew'].apply(crew)

In [95]:
movie.sample(5)

,title,genres,id,keywords,overview,production_companies,vote_average,cast,crew,tagline,vote_count
3007,Dogma,"[Fantasy, Comedy, Adventure]",1832,"[angel, wisconsin, church service, church, aft...",The latest battle in the eternal war between G...,"[Lions Gate, View Askew Productions]",6.8,"[Ben Affleck, Matt Damon, Linda Fiorentino, Ja...","[Kevin Smith, Kevin Smith]",It can be Hell getting into Heaven,823
3978,Barry Munday,"[Comedy, Drama, Romance]",44594,"[based on novel, letter, paternity, castration...","Barry Munday, a libido-driven wage slave who s...","[Prospect Pictures, Corner Store Entertainment...",6.3,"[Patrick Wilson, Malcolm McDowell, Judy Greer,...",[Chris D'Arienzo],A comedy that hits you right where it counts.,22
1807,The Curse of the Jade Scorpion,"[Comedy, Crime, Mystery, Romance, Thriller]",2779,"[hypnosis, independent film]","CW Briggs is a veteran insurance investigator,...","[DreamWorks SKG, Gravier Productions]",6.5,"[Dan Aykroyd, Helen Hunt, Woody Allen, Charliz...",[Woody Allen],Love stings,165
1680,United Passions,[Drama],271331,[soccer],"An epic, untold story that brings to life the ...","[Thelma Films, Leuviah Films]",3.0,"[Tim Roth, Sam Neill, Thomas Kretschmann, Géra...",[Frédéric Auburtin],Every dream has it's own rules,16
301,Cloud Atlas,"[Drama, Science Fiction]",83542,"[clone, future, dystopia, ensemble cast, durin...",A set of six nested stories spanning time betw...,"[Anarchos Productions, X-Filme Creative Pool, ...",6.6,"[Tom Hanks, Halle Berry, Jim Broadbent, Hugo W...","[Tom Tykwer, Lilly Wachowski, Lana Wachowski]",Everything is Connected,2977

In [96]:
movie["genres"] = movie["genres"].apply(lambda x: " ".join(x))
movie["keywords"] = movie["keywords"].apply(lambda x: " ".join(x))
movie["cast"] = movie["cast"].apply(lambda x: " ".join(x))
movie["crew"] = movie["crew"].apply(lambda x: " ".join(x))
movie["production_companies"] = movie["production_companies"].apply(lambda x: " ".join(x))

In [97]:
movie['tags']=movie['genres']*4+movie['keywords']*4+movie['production_companies']+movie['overview']+movie['cast']+movie['crew']+movie['tagline']

In [98]:
v = movie['vote_count']
R = movie['vote_average']

C = movie['vote_average'].mean()
m = movie['vote_count'].quantile(0.90)   

movie['weighted_rating'] = (v/(v+m) * R) + (m/(v+m) * C)

In [99]:
movie = movie.drop(columns=['overview','genres','keywords','cast','crew','production_companies','tagline','vote_count','vote_average'])

In [102]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

vectors = tfidf.fit_transform(movie["tags"]).toarray()

In [103]:
vectors.shape

(4809, 5000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [105]:
similarity.shape

(4809, 4809)

In [110]:
def recommend(movie):
    
    index = concatenate_df[concatenate_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x: x[1])
    similar = distances[1:11]
    top_similar = sorted(similar,key=lambda x: movie.iloc[x[0]].weighted_rating,reverse=True)
    recommended_movie_names = []
    recommended_movie_posters = []
    for i in top_similar[:5]:
        movie_id = movie.iloc[i[0]].id
        recommended_movie_names.append(movies.iloc[i[0]].title)

    return recommended_movie_names

In [111]:
recommend('Toy Story 2')

['The Vow',
 'Toy Story 3',
 'The Lego Movie',
 'Anastasia',
 'Book of Shadows: Blair Witch 2']

In [114]:
import pickle

pickle.dump(movie, open("movies.pkl", "wb"))